version: '3.8'

networks:
    app:
        name: app

services:
    php:
        build:
            context: .
            dockerfile: php.dockerfile
        container_name: php
        volumes:
            - ./src:/var/www/html
        networks:
            - app
    
    mysql:
        image: mysql:8.0.28
        container_name: mysql
        environment:
            MYSQL_DATABASE: appdb
            MYSQL_USER: user
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        networks:
            - app
        ports:
            - 4306:3306
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./mysql/log:/var/log/mysql
        # Fix mbind error
        # This is could be a initial fix for now, this might disable the mysql security features
        # https://thegeekbin.com/mbind-operation-not-permitted-docker-mysql/
        security_opt:
            - seccomp:unconfined
    
    nginx: 
        build:
            context: .
            dockerfile: nginx.dockerfile 
        container_name: nginx
        networks:
            - app
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./src:/var/www/html
    
    # apache:
    #     build:
    #         context: .
    #         dockerfile: apache.dockerfile
    #     container_name: apache
    #     networks:
    #         - app
    #     ports:
    #         - 80:80
    #         - 443:443            
    #     volumes:
    #         - ./src:/var/www/html
