version: '3.8'

networks:
    app:
        name: app

services:
    php:
        image: php:8.1.3-fpm-alpine
        container_name: php
        networks:
            - app
    
    mysql:
        image: mysql:8.0.28
        container_name: mysql
        environment:
            MYSQL_DATABASE: appdb
            MYSQL_USER: user
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        networks:
            - app
    
    nginx: 
        build:
            context: .
            dockerfile: nginx.dockerfile 
        container_name: nginx
        networks:
            - app
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./src:/var/www/html

