version: '3.8'

networks:
    ldb-app:
        name: ldb-app

services:
    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: ldb-php
        volumes:
            - ./src:/var/www/html:delegated
        depends_on:
            - mysql
        networks:
            - ldb-app

    mysql:
        image: mysql:8.0.28
        container_name: ldb-mysql
        environment:
            MYSQL_DATABASE: appdb
            MYSQL_USER: user
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        networks:
            - ldb-app
        ports:
            - 4306:3306
        volumes:
            - ./.mysqldata:/var/lib/mysql
            # - ./docker/mysql/log:/var/log/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        # Fix mbind error
        # This is could be a initial fix for now, this might disable the mysql security features
        # https://thegeekbin.com/mbind-operation-not-permitted-docker-mysql/
        security_opt:
            - seccomp:unconfined

    nginx:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        container_name: ldb-nginx
        depends_on:
            - php
            - mysql
            - redis
        networks:
            - ldb-app
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./src:/var/www/html:delegated

    # apache:
    #     build:
    #         context: .
    #         dockerfile: apache.dockerfile
    #     container_name: apache
    #     networks:
    #         - app
    #     ports:
    #         - 80:80
    #         - 443:443            
    #     volumes:
    #         - ./src:/var/www/html

    composer:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: ldb-composer
        volumes:
            - ./src:/var/www/html:delegated
        entrypoint: [ "composer" ]
        networks:
            - ldb-app

    artisan:
        user: 1000:1000
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: ldb-artisan
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        entrypoint: [ "php", "artisan" ]
        networks:
            - ldb-app

    npm:
        user: node:node
        build:
            context: .
            dockerfile: ./docker/npm/Dockerfile
        container_name: ldb-npm
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        entrypoint: ["npm"]
        networks:
            - ldb-app

    phpunit:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: ldb-phpunit
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        entrypoint:
            [
                "/var/www/html/vendor/bin/phpunit",
                "--configuration=/var/www/html/phpunit.xml"
            ]
        networks:
            - ldb-app

    redis:
        image: redis:latest
        container_name: ldb-redis
        ports:
            - 6379:6379
        networks:
            - ldb-app

    scheduler:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: ldb-scheduler
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        entrypoint: [ "php", "artisan", "schedule:work" ]
        networks:
            - ldb-app

    adminer:
        image: adminer
        restart: always
        container_name: ldb-adminer
        ports:
            - 8080:8080
        networks:
            - ldb-app
