version: '3.8'

networks:
    app:
        name: app

services:
    php:
        build:
            context: .
            dockerfile: ./docker/php/prod.Dockerfile
        container_name: php
        depends_on:
            - mysql
        networks:
            - app
    
    mysql:
        image: mysql:8.0.28
        container_name: mysql
        environment:
            MYSQL_DATABASE: appdb
            MYSQL_USER: user
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        networks:
            - app
        ports:
            - 4306:3306
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./mysql/log:/var/log/mysql
            - ./mysql/my.cnf:/etc/mysql/my.cnf
        # Fix mbind error
        # This is could be a initial fix for now, this might disable the mysql security features
        # https://thegeekbin.com/mbind-operation-not-permitted-docker-mysql/
        security_opt:
            - seccomp:unconfined
    
    nginx:
        build:
            context: .
            dockerfile: ./docker/nginx/prod.Dockerfile 
        container_name: nginx
        depends_on:
            - php
            - mysql
            - redis
        networks:
            - app
        ports:
            - 80:80
            - 443:443

    composer:
        user: 1000:1000
        image: composer:latest
        container_name: composer
        working_dir: /var/www/html
        networks:
            - app

    artisan:
        build:
            context: .
            dockerfile: ./docker/php/prod.Dockerfile
        container_name: artisan
        working_dir: /var/www/html
        entrypoint: ["php", "artisan"]
        networks:
            - app

    npm:
        image: node:17.5.0
        container_name: npm
        working_dir: /var/www/html
        entrypoint: ["npm"]
        networks:
            - app

    phpunit:
        build:
            context: .
            dockerfile: ./docker/php/prod.Dockerfile
        container_name: phpunit
        depends_on:
            - mysql
        working_dir: /var/www/html
        entrypoint: ["/var/www/html/vendor/bin/phpunit"]
        networks:
            - app

    redis:
        image: redis:latest
        container_name: redis
        ports:
            - 6379:6379
        networks:
            - app

    scheduler:
        build:
            context: .
            dockerfile: ./docker/php/prod.Dockerfile
        container_name: scheduler
        working_dir: /var/www/html
        entrypoint: ["php", "artisan", "schedule:work"]
        networks:
            - app
    certbot:
        image: certbot/certbot
        volumes:
        - ./docker/certbot/conf:/etc/letsencrypt
        - ./docker/certbot/www:/var/www/certbot
