export const UPDATE_TICKET = 'UPDATE-TICKET';
export const COMMENT = 'COMMENT';
export const ADD_TAGS_TO_TICKET = 'ADD-TAGS-TO-TICKET';
export const ADD_FILES_TO_TICKET = 'ADD-FILES-TO-TICKET';
export const COMMENT_MENTION = 'COMMENT-MENTION';
export const ASSIGN_TICKET = 'ASSIGN-TICKET';
export const CREATE_TICKET = 'CREATE-TICKET';

export const avatarType = [
  UPDATE_TICKET,
  COMMENT,
  COMMENT_MENTION,
  ASSIGN_TICKET,
];
export const iconType = [
  ADD_TAGS_TO_TICKET,
  ADD_FILES_TO_TICKET,
  CREATE_TICKET,
];
