version: 2

jobs:
  build-fe:
    working_directory: ~/project/src
    docker: 
      - image: cimg/node:20.12.2-browsers
    steps:
      - checkout:
          path: ~/project
      - run: 
          name: "Installing node dependencies"
          command: npm install
      - run: 
          name: "Building frontend"
          command: npm run build
      - run:
          name: "Directory checking"
          command: ls -lah public

  build-be:
    docker:
      - image: cimg/php:8.1.27-browsers

    steps:
      - attach_workspace:
          at: ~/project/src

      - run:
          name: "Directory checking"
          command: ls -lah ~/project/src

      - run:
          name: "Directory checking"
          command: cd ~/project/src

      - run: 
          name: "Prepare Environment"
          command: |
            sudo apt update
            sudo docker-php-ext-install zip pdo pdo_mysql bcmath

      - run:
          name: "Create Environment File"
          command: |
            mv .env.testing .env

      # - restore_cache:
      #     keys:
      #       # "composer.lock" can be used if it is committed to the repo
      #       - v1-dependencies-{{ checksum "composer.json" }}
      #       # fallback to using the latest cache if no exact match is found
      #       - v1-dependencies-

      - run:
          name: "Install Dependencies"
          command: composer install -n --prefer-dist

      # - save_cache:
      #     key: v1-dependencies-{{ checksum "composer.json" }}
      #     paths:
      #       - ./vendor

      - run:
          name: "Install Dependencies"
          command: php artisan key:generate

      # - run: touch storage/testing.sqlite
      - run:
          name: "Run testing"
          command: ./vendor/bin/phpunit

  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy over SSH
          command: |
            ssh -o StrictHostKeyChecking=no docker@laravel-base.com 'cd /home/docker/site && git fetch origin master && git reset --hard origin/main && git pulll origin main && docker-compose -f docker-compose.prod.yml up -d --build nginx'

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-fe
      - build-be:
          requires:
            - build-fe

